---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/alexica/docker/hass/data:/config
        #- /dev/serial/by-id:/dev/serial/by-id  
        # ports:
        # - 8123:8123 #optional
    devices:
      #- /dev/bus/usb/002/002:/dev/bus/usb/002/002
      #- /dev/bus/usb/002/003:/dev/bus/usb/002/003 #optional
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
